server:
  applicationConnectors:
    - type: http
      port: 8095
  adminConnectors:
    - type: http
      port: 8096

defaultSize: 5
database:
  driverClass: org.h2.Driver
  user: admin
  password: test
  url: jdbc:h2:file:./dropwizard-todoApp;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
   charSet: UTF-8  
   hibernate.dialect: org.hibernate.dialect.H2Dialect
   hibernate.show_sql: true
   hibernate.generate_statistics: false
   hibernate.hbm2ddl.auto: update # validates schema when service is started